// <auto-generated />
using System;
using Aurora.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aurora.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(AuroraDbContext))]
    [Migration("20221126091343_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aurora.Domain.Systems.Permissions.Permission", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2022, 11, 26, 17, 13, 43, 366, DateTimeKind.Local).AddTicks(8414));

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ParentId")
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("tb_permission", (string)null);
                });

            modelBuilder.Entity("Aurora.Domain.Systems.RolePermissions.RolePermission", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2022, 11, 26, 17, 13, 43, 367, DateTimeKind.Local).AddTicks(5056));

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("PermissionId")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)");

                    b.HasKey("Id");

                    b.ToTable("tb_role_permission", (string)null);
                });

            modelBuilder.Entity("Aurora.Domain.Systems.Roles.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2022, 11, 26, 17, 13, 43, 367, DateTimeKind.Local).AddTicks(6011));

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)");

                    b.HasKey("Id");

                    b.ToTable("tb_role", (string)null);
                });

            modelBuilder.Entity("Aurora.Domain.Systems.Tenants.Tenant", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2022, 11, 26, 17, 13, 43, 368, DateTimeKind.Local).AddTicks(2525));

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ParentId")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)");

                    b.HasKey("Id");

                    b.ToTable("tb_tenant", (string)null);
                });

            modelBuilder.Entity("Aurora.Domain.Systems.UserRoles.UserRole", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2022, 11, 26, 17, 13, 43, 368, DateTimeKind.Local).AddTicks(4223));

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)");

                    b.HasKey("Id");

                    b.ToTable("tb_user_role", (string)null);
                });

            modelBuilder.Entity("Aurora.Domain.Systems.Users.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2022, 11, 26, 17, 13, 43, 368, DateTimeKind.Local).AddTicks(5153));

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("tb_user", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
